sudo: required
language: node_js
notifications:
  email: false
node_js:
  - "lts/*"
services:
  - docker
before_install:
  - docker build -t marudor/bahnhofsabfahrten .
install:
  - 
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push marudor/bahnhofsabfahrten;
    fi
